version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_appliance
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "spgroup"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "appliance"
    volumes:
      - mysql_data:/var/lib/mysql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mysql

volumes:
  mysql_data: